### ISSUE TITLE
Weather Widget 

### ISSUE THREAD

**Issue by john494** [john494/SmartMirror#12]
Create a weather widget to fetch current weather
- [ ] Research where to get weather from 
- [ ] Implement widget

**Comment by michaelkulbacki** [comment]
- [ ]  Check if can sync with the current weather icons pack, [Supported APIs](https://erikflowers.github.io/weather-icons/api-list.html)

**Comment by john494** [comment]
@michaelkulbacki i have heard good things about Weather underground, we've seen terrible with yahoo, no idea about the .io one

**Comment by michaelkulbacki** [comment]
@john494 Yea totally fine we will find out what works best [Dark Sky API](https://darksky.net/dev/docs) looks pretty solid and can work with icons
