### ISSUE TITLE
Phone app update Facebook feed on server

### ISSUE THREAD

**Issue by john494** [john494/SmartMirror#39]
Phone app should log into Facebook and fill server

**Comment by ajkirschner** [comment]
https://www.sitepoint.com/integrating-the-facebook-api-with-android/

**Comment by ajkirschner** [comment]
https://code.tutsplus.com/tutorials/quick-tip-add-facebook-login-to-your-android-app--cms-23837

**Comment by ajkirschner** [comment]
- [x] Add Facebook app ID to SmartMirror app.
- [x] Generate release key hashes and add to Facebook developer dashboard
- [x] Be able to login to Facebook in app
- [x] Pull relevant data from Facebook (Tagged posts)
- [x] Push data to server
- [x] Merge with phoneapp
- [x] Merge with develop

**Comment by ajkirschner** [comment]
https://www.numetriclabz.com/android-facebook-integration-and-login/#Add_FacebookActivity_In_Manifest_File 

This was what worked for what I wanted to do with the app.

**Comment by ajkirschner** [comment]
When the app is run, log into Facebook and restart the activity by flipping the phone to landscape or restarting the app. That will allow the app to post statuses to the server. This functionality can be changed but for our purposes at this time it is sufficient. Server page is http://jarvis.cse.buffalo.edu/mine/facebookinfo
