### ISSUE TITLE
Get logging working

### ISSUE THREAD

**Issue by john494** [john494/SmartMirror#46]
Set up logging for phone app

**Comment by ajkirschner** [comment]
- [x] Alex
- [x] John

**Comment by john494** [comment]
For some reason logcat won't work in android studios for me.  I run through command line.  make sure you have adb installed on your computer then `adb logcat SmartMirror:<D|E|I> *:S` to show debug/error/info for only smart mirror app suppressing everything else

**Comment by ajkirschner** [comment]
I don't know why it would not work for you but I mean I guess as long as you can see the logs somehow it shouldn't matter.
