### ISSUE TITLE
Get location from inputted latitude and longitude

### ISSUE THREAD

**Issue by michaelkulbacki** [john494/SmartMirror#53]
Input the lat and long and get a location, ideally get users location first then convert it

**Comment by ajkirschner** [comment]
I think the Facebook api allows me to get the town of the person that signs in, if that helps you with anything.

**Comment by michaelkulbacki** [comment]
@ajkirschner i can make a get request to google maps using lat and long, and it returns a JSON object with all my info, but when the user turns it on we need to grab the Lat and Long so if i cant do that with javascript we could use fb

**Comment by ajkirschner** [comment]
Just let me know. Looking at the Facebook functions it looks like I might even be able to get lat and long for their location
